name: PosterLlama
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.08.22
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.12
  - pip=23.3
  - python=3.9.18
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - absl-py==2.0.0
      - accelerate==0.24.1
      - aiofiles==23.2.1
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - altair==5.1.2
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - anyio==3.7.1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - babel==2.13.1
      - beautifulsoup4==4.12.2
      - bitsandbytes==0.41.2.post2
      - bleach==6.1.0
      - braceexpand==0.1.7
      - certifi==2022.12.7
      - cffi==1.16.0
      - charset-normalizer==2.1.1
      - click==8.1.7
      - cmake==3.25.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - comm==0.2.0
      - contextlib2==21.6.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - datasets==2.16.1
      - debugpy==1.8.0
      - decorator==5.1.1
      - deepspeed==0.13.1
      - defusedxml==0.7.1
      - diffusers==0.24.0
      - dill==0.3.7
      - docstring-parser==0.15
      - easydict==1.11
      - einops==0.7.0
      - exceptiongroup==1.1.3
      - executing==2.0.1
      - fastapi==0.104.1
      - fastjsonschema==2.19.0
      - ffmpy==0.3.1
      - filelock==3.9.0
      - fire==0.5.0
      - fonttools==4.44.3
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2023.10.0
      - gradio==3.50.2
      - gradio-client==0.6.1
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==1.0.2
      - httpx==0.25.1
      - huggingface-hub==0.19.4
      - humanfriendly==10.0
      - idna==3.4
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.1
      - install==1.3.5
      - iopath==0.1.10
      - ipykernel==6.26.0
      - ipython==8.17.2
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.1
      - jupyter==1.0.0
      - jupyter-client==8.6.0
      - jupyter-console==6.6.3
      - jupyter-core==5.5.0
      - jupyter-events==0.9.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.10.1
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.8
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.25.1
      - jupyterlab-widgets==3.0.9
      - kiwisolver==1.4.5
      - lightning-utilities==0.10.0
      - lit==15.0.7
      - loguru==0.7.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mistune==3.0.2
      - ml-collections==0.1.1
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.15
      - nbclient==0.9.0
      - nbconvert==7.11.0
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - networkx==3.0
      - ninja==1.11.1.1
      - notebook==7.0.6
      - notebook-shim==0.2.3
      - numpy==1.24.1
      - omegaconf==2.3.0
      - opencv-python==4.8.1.78
      - orjson==3.9.10
      - overrides==7.4.0
      - packaging==23.2
      - pandas==2.1.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - path==16.7.1
      - peft==0.6.2
      - pexpect==4.8.0
      - pillow==9.3.0
      - platformdirs==4.0.0
      - portalocker==2.8.2
      - prdc==0.2
      - prometheus-client==0.18.0
      - prompt-toolkit==3.0.41
      - protobuf==4.25.1
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pyarrow==14.0.2
      - pyarrow-hotfix==0.6
      - pycocotools==2.0.7
      - pycparser==2.21
      - pydantic==2.5.2
      - pydantic-core==2.14.5
      - pydub==0.25.1
      - pygments==2.16.1
      - pynvml==11.5.0
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - python-multipart==0.0.6
      - pytorch-fid==0.3.0
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - referencing==0.31.0
      - regex==2023.10.3
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.0
      - rpds-py==0.13.0
      - safetensors==0.4.0
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - seaborn==0.13.0
      - semantic-version==2.10.0
      - send2trash==1.8.2
      - sentencepiece==0.1.99
      - shellingham==1.5.4
      - shtab==1.6.5
      - six==1.16.0
      - slack-sdk==3.26.1
      - sniffio==1.3.0
      - soupsieve==2.5
      - stack-data==0.6.3
      - starlette==0.27.0
      - sympy==1.12
      - termcolor==2.4.0
      - terminado==0.18.0
      - threadpoolctl==3.2.0
      - timm==0.9.10
      - tinycss2==1.2.1
      - tokenizers==0.15.0
      - tomli==2.0.1
      - tomlkit==0.12.0
      - toolz==0.12.0
      - torch==2.0.1+cu117
      - torch-geometric==2.4.0
      - torchaudio==2.0.2+cu117
      - torchmetrics==1.2.1
      - torchvision==0.15.2+cu117
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.13.0
      - transformers==4.35.2
      - triton==2.0.0
      - typer==0.9.0
      - types-python-dateutil==2.8.19.14
      - typing-extensions==4.8.0
      - tyro==0.6.3
      - tzdata==2023.3
      - uri-template==1.3.0
      - urllib3==1.26.13
      - uvicorn==0.24.0.post1
      - wcwidth==0.2.10
      - webcolors==1.13
      - webdataset==0.2.77
      - webencodings==0.5.1
      - websocket-client==1.6.4
      - websockets==11.0.3
      - widgetsnbextension==4.0.9
      - xxhash==3.4.1
      - yarl==1.9.4
      - zipp==3.17.0